### ISSUE TITLE
BUGFIX: give a better error message for package name heuristic failure

### ISSUE THREAD

**Issue by nathanjmcdougall** [nathanjmcdougall/suiteas#98]
If you have three folders at root level:

- mypkg
- folder2
- tests

And this config:
```TOML
[tool.suiteas]
src_rel_path = '.'
unittest_dir_name = "."
```

Then unit tests for `folder2` are sought, incorrectly. The error message could be better:

```
FileNotFoundError: Could not find unit test directory of folder2 at ...
```
